# Generated by Django 2.1.2 on 2018-12-07 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_check',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last check Time'),
        ),
    ]
