# Generated by Django 2.1.2 on 2018-12-07 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_auto_20181207_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 16, 45, 42, 342542), verbose_name='last check Time'),
        ),
    ]
